test: Loader Component 100% Test Coverage and Fix Uncovered Lines
PalisadoesFoundation/talawa-admin pull request #1047
Opened 2023-11-06 14:18 UTC by akhilender-bongirwar

**What kind of change does this PR introduce?**

- Improved the test coverage for the Loader component, addressing the previously uncovered lines and ensuring that all tests pass successfully.
- Added a test to ensure that the component renders correctly with a custom 'sm' size. I verified that both the spinner-wrapper and spinner elements are present and that the correct class is applied.
- Added a test to ensure that the component renders correctly with a 'lg' size. I verified that the spinner element has the appropriate class.
- Added a test to ensure that the component renders correctly with an 'xl' size. I verified that the spinner element has the correct class.

**Issue Number:**

Fixes  #1026 

**Did you add tests for your changes?**
 Yes

**Snapshots/Videos:**
**Before**
![prevTest](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/0d2e1be6-1ce4-46d4-9a04-0d250c10478f)
**After**
![testsLoader100](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/cafa4eb3-f0f0-493b-adaa-ebc43a0b7ecf)

**If relevant, did you update the documentation?**
No

**Summary**
With these new tests, I now have 100% test coverage, and there are no more uncovered lines. The Loader component is thoroughly tested for different size scenarios, and all tests pass successfully.

**Does this PR introduce a breaking change?**
 No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2023-11-08 04:54 UTC, akhilender-bongirwar commented
@Ayush0Chaudhary, could you please review this PR .

2023-11-08 07:16 UTC, Ayush0Chaudhary commented
@akhilender-bongirwar please write the tests, and bring them to acceptable level

2023-11-11 15:24 UTC, noman2002 approved these changes
Looks good to me. Expect the acceptable code coverage is failing because its 95% and its not possible to reach there in this PR. We can merge this.

2023-11-11 15:25 UTC, noman2002 commented
@rishav-jha-mech @beingnoble03 Please review once.

2023-11-13 18:20 UTC, beingnoble03 commented on src/components/Loader/Loader.test.tsx
> +    expect(spinnerWrapper).toHaveClass('_spinner_wrapper_1vy2z_1');
You should not include these classes which are generated on build time. Please remove this check.
```suggestion
```

2023-11-13 18:25 UTC, beingnoble03 commented on src/components/Loader/Loader.test.tsx
> +      '_spinnerSm_1vy2z_21 spinner-border text-primary'
Same remove `_spinnerSm_1vy2z_21` from check.

2023-11-13 18:25 UTC, beingnoble03 commented on src/components/Loader/Loader.test.tsx
> +      '_spinnerLg_1vy2z_15 spinner-border text-primary'
Same remove `_spinnerLg_1vy2z_15` from check.

2023-11-13 18:25 UTC, beingnoble03 requested changes
Some changes.

2023-11-14 09:13 UTC, akhilender-bongirwar commented
@beingnoble03, This is my first time writing tests, and I initially believed that checking for classNames also would enhance the test coverage in the codecov report. But validating classes assigned during runtime is inappropriate. Thank you for bringing this to my attention.  I appreciate your feedback  : )

2023-11-14 12:00 UTC, beingnoble03 approved these changes
LGTM.

2023-11-14 17:12 UTC, palisadoes approved these changes

2023-11-14 17:13 UTC, merged