[#1123] Changes position and text of "All Organizations" button
PalisadoesFoundation/talawa-admin pull request #1124
Opened 2023-12-05 09:49 UTC by adi790uu

**What kind of change does this PR introduce?**

This PR renames the "All Organizations" button to "My Organizations" and fixes its postion as specified in the issue.

**Issue Number:**

Fixes #1123 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

[Screencast from 05-12-23 03:14:37 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/543631e7-37ba-4527-a0f6-be5c8ccda093)

**If relevant, did you update the documentation?**

No

**Summary**

This pull request addresses the specified issue by renaming the "All Organizations" button to "My Organizations" and adjusting its position to enhance the UI/UX.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-05 14:59 UTC, aashimawadhwa commented
Please share a screenshot and  
Please make the code coverage 100% for the modified file. It has been declining overall and we need to make sure we get it back up to make our code more stable.
@adi790uu

2023-12-05 15:43 UTC, noman2002 requested changes
Please fix the failing test.

2023-12-05 19:43 UTC, adi790uu commented
Ok will work on it!

2023-12-06 17:02 UTC, noman2002 commented
The coverage is dropping significantly. Please get the coverage to 100% for the files you edited and merge the latest code into this PR.

2023-12-07 18:08 UTC, adi790uu commented
@aashimawadhwa @beingnoble03  The coverage is down because of files which are not under the scope of this pull request and issue, what should I do from here?

2023-12-08 05:51 UTC, noman2002 requested changes
Remove the mentioned unnecessary changes.

2023-12-08 05:51 UTC, noman2002 commented on src/GraphQl/Queries/Queries.ts
>  // Check Auth
Unnecessary change.

2023-12-08 05:51 UTC, noman2002 commented on src/components/OrganizationScreen/OrganizationScreen.tsx
>  const organizationScreen = ({
Unnecessary change.

2023-12-08 17:01 UTC, aashimawadhwa approved these changes

2023-12-08 17:06 UTC, palisadoes approved these changes

2023-12-09 16:20 UTC, aashimawadhwa approved these changes

2023-12-09 16:21 UTC, aashimawadhwa commented
@palisadoes  this can be merged

2023-12-09 16:31 UTC, palisadoes approved these changes

2023-12-09 16:32 UTC, palisadoes commented
@noman2002 please review. We can't merge until you have dismissed your previous requests for change.

2023-12-10 16:48 UTC, noman2002 approved these changes

2023-12-10 16:48 UTC, merged

2023-12-12 12:22 UTC, noman2002 commented
@adi790uu Need to revert this. This should be develop branch not on main.