Fixed the toast message for deleting an org.
PalisadoesFoundation/talawa-admin pull request #1128
Opened 2023-12-05 16:03 UTC by AmitSharma512

**What kind of change does this PR introduce?**

This PR solves the issue of the toast message not being displayed while deleting the organization.

**Issue Number:**

Fixes #1108 

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/07138238-720d-4d4e-b31c-9b190ccb8a1a

**Summary**

Previously, When we delete an organization or a sample organization, no toast message of success was shown, and instead of using React Routing, window.location.replace was used. This PR solves all the above issues.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-05 17:01 UTC, palisadoes commented
Please fix the failing tests.

2023-12-06 16:51 UTC, noman2002 requested changes

2023-12-06 16:51 UTC, noman2002 commented on src/components/DeleteOrg/DeleteOrg.tsx
> +        errorHandler(t, error);
Write tests for these lines.

2023-12-06 16:51 UTC, noman2002 commented on src/components/DeleteOrg/DeleteOrg.tsx
> +        history.push('/orglist');
These too.

2023-12-06 16:57 UTC, AmitSharma512 commented
@noman2002 I tried to write the tests, but every time, I got an unexpected error that I was not able to solve.
According to my knowledge, my basics are correct, but then also tests are not passing.

2023-12-06 17:05 UTC, noman2002 commented
@AmitSharma512 Ask in the slack channel, someone will help you out.

2023-12-10 16:49 UTC, noman2002 commented
@AmitSharma512 Any update on this one ?

2023-12-10 17:02 UTC, AmitSharma512 commented
@noman2002 actually I was out of station for the last 3 days, from tomorrow I will be back to work.

2023-12-12 01:32 UTC, palisadoes commented
The test code coverage is dropping significantly with this PR. Please get to at least 95% coverage for all your edited files. Though there may be issues to increase the coverage for the file, the aim is for them to reach 100% coverage

2023-12-23 03:24 UTC, palisadoes commented
Is this still being worked on?

2023-12-23 07:01 UTC, AmitSharma512 commented
@palisadoes yes

2023-12-29 18:34 UTC, noman2002 commented
@AmitSharma512 Its been more than 3 weeks since this PR is open. Please update on this or I have to close it.

2023-12-29 21:28 UTC, palisadoes commented
Closing and unassigning. It's been too long and the task is simple

2023-12-29 21:28 UTC, closed without merging