Code coverage: Updated code coverage for src/components/UserPortal/Login/Login.tsx
PalisadoesFoundation/talawa-admin pull request #1209
Opened 2023-12-16 18:25 UTC by pateldivyesh1323

**What kind of change does this PR introduce?**

Updated test coverage of `src/components/UserPortal/Login/Login.tsx`

**Issue Number:**

Fixes #1032

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/8707d9c4-4b56-4026-b28a-010ff754552f)

**Summary**
- As far as I understood there is no case which will enter into the else condition
- The else condition was made in admin portal to filter out non-admin users 
- Here the response without data will only come in form of error and always go in the catch block

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-17 18:25 UTC, noman2002 approved these changes

2023-12-17 19:29 UTC, palisadoes requested changes
It looks like you got the code coverage up by removing functionality. If this is son, it is not in the spirit of our community and the desire to have a better product. @noman2002 Please verify.

Please write code that tests the code base without removing functionality

2023-12-17 19:29 UTC, palisadoes commented on src/components/UserPortal/Login/Login.tsx
> -          toast.warn(t('notAuthorised'));
It looks like you got the code coverage up by removing functionality. If this is son, it is not in the spirit of our community and the desire to have a better product. @noman2002 Please verify.

2023-12-17 19:29 UTC, palisadoes commented on src/components/UserPortal/Login/Login.tsx
> -          toast.warn(t('notAuthorised'));
Please write code that tests the code base without removing functionality

2023-12-18 11:16 UTC, noman2002 commented
@pateldivyesh1323 Make sure not to repeat this type of behavior.

2023-12-18 12:30 UTC, pateldivyesh1323 commented
@palisadoes  I do not have any intention of breaking things. I understand you didn't liked the way I implemented it and I also explained in this PR comment why I did it this way.

@noman2002 Can you suggest a case in which the `else` condition will become true or a better way to implement this? also I didn't understood why you approved this PR on first hand.

2023-12-19 15:00 UTC, palisadoes commented
@noman2002 Please respond

2023-12-19 18:35 UTC, noman2002 commented
> @palisadoes I do not have any intention of breaking things. I understand you didn't liked the way I implemented it and I also explained in this PR comment why I did it this way.
> 
> @noman2002 Can you suggest a case in which the `else` condition will become true or a better way to implement this? also I didn't understood why you approved this PR on first hand.

I mistakenly approved it earlier, it was my fault.

2023-12-23 08:49 UTC, pateldivyesh1323 commented
@noman2002, @palisadoes I am closing this as I am not able to find something that can lead to any conclusion.

2023-12-23 08:49 UTC, closed without merging