Corrected cancel button functionality
PalisadoesFoundation/talawa-admin pull request #1215
Opened 2023-12-20 04:01 UTC by Anvita0305

**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**
#1211 

**Did you add tests for your changes?**
N/A

**Snapshots/Videos:**
[Screencast from 20-12-23 09:04:25 AM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/e62f5926-8e17-4eda-88fc-34bf4607ae51)

**If relevant, did you update the documentation?**
N/A

**Summary**
1. Corrected cancel button functionality
2. Fixed button's CSS

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2023-12-20 18:32 UTC, noman2002 requested changes

2023-12-20 18:32 UTC, noman2002 commented on src/components/OrgListCard/OrgListCard.tsx
> +    console.log('clicked!');
Remove logs.

2023-12-21 03:16 UTC, Anvita0305 commented on src/components/OrgListCard/OrgListCard.tsx
> +    console.log('clicked!');
Done, please check.

2023-12-23 18:22 UTC, noman2002 requested changes
Please write the tests for missing lines.

2023-12-27 09:38 UTC, noman2002 requested changes
Please fix the failing tests.

2023-12-31 16:03 UTC, noman2002 commented
@Anvita0305 Any update on this ?

2023-12-31 17:10 UTC, Anvita0305 commented
Will start working this week

2024-01-01 15:39 UTC, palisadoes commented
Please fix the conflicting files

2024-01-14 14:05 UTC, Anvita0305 commented
fixed conflicting files @palisadoes @noman2002

2024-01-14 15:12 UTC, palisadoes commented
Please fix the conflicting file, it just came up

2024-01-14 18:08 UTC, palisadoes commented
Please review:

- @rishav-jha-mech
- @aashimawadhwa
- @noman2002
- @ttaylor92

2024-01-15 02:38 UTC, Anvita0305 commented
Can someone please explain why this check is failing as I haven't done any changes to schema.graphql. @noman2002 
![Screenshot 2024-01-15 023522](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/dc58f49e-3c78-49be-834c-9b8cb93a1d30)

2024-01-15 03:07 UTC, palisadoes commented
We discovered a bug in the introspection test. It will be fixed here
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1429

2024-01-15 03:08 UTC, palisadoes commented
Reviewers please review this PR. Ignore the failing introspection test for now.

2024-01-16 05:11 UTC, rishav-jha-mech commented
Closing this due to inactivity

2024-01-16 05:11 UTC, closed without merging