Code Coverage for DeleteOrg.tsx
PalisadoesFoundation/talawa-admin pull request #1216
Opened 2023-12-20 16:02 UTC by ShatilKhan

Fixes #1066

**Did you add tests for your changes?**
Yes 

**Summary**

## Test for Rendering Delete Button

This test checks if the delete button is rendered correctly when the `canDelete` prop is `true`. It renders the `DeleteOrg` component and then checks if the delete button (identified by the `data-testid` attribute `openDeleteModalBtn`) is present in the document.

## Test for Opening Delete Modal

This test checks if the delete modal appears when the delete button is clicked. It renders the `DeleteOrg` component, simulates a click event on the delete button, and then checks if the delete modal (identified by the `data-testid` attribute `orgDeleteModal`) is present in the document.

## Test for Closing Delete Modal

This test checks if the delete modal closes when the close button is clicked. It renders the `DeleteOrg` component, simulates a click event on the delete button to open the modal, simulates another click event on the close button (identified by the `data-testid` attribute `closeDelOrgModalBtn`), and then checks if the delete modal is not present in the document.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-20 18:30 UTC, noman2002 requested changes
Please fix the type errors.

2023-12-20 19:09 UTC, ShatilKhan commented
> Please fix the type errors.
Can you explain a bit on what change you're referring to please?
An example would be appreciated

2023-12-21 00:14 UTC, palisadoes commented
Please fix the failing test

2023-12-21 01:49 UTC, ShatilKhan commented
Yes I've found the errors, working on fixing them

2023-12-21 08:57 UTC, aashimawadhwa commented
but this issue is not assigned to you? @ShatilKhan

2023-12-21 10:42 UTC, ShatilKhan commented
> but this issue is not assigned to you? @ShatilKhan

It was originally assigned to me
Unassigned as I couldn’t make the PR in time
I finally made the PR last night

2023-12-21 12:41 UTC, palisadoes commented
Unfortunately, there isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready. 

We understand the difficulty in your situation but we have to balance dormant issues that get no attention and the need for everyone to get a chance. Please look for or create other issues to work on.

Closing

2023-12-21 12:41 UTC, closed without merging