Improper positioning of Event Statistics in the mobile view
PalisadoesFoundation/talawa-admin pull request #1308
Opened 2023-12-27 20:09 UTC by duplixx

**What kind of change does this PR introduce?**

**Issue Number:** #1286 

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

2023-12-27 20:21 UTC, Cioppolo14 commented
@duplixx Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

2023-12-27 20:35 UTC, duplixx commented
@Cioppolo14 i have fixed, Can you check it.
Thanks!!

2023-12-28 18:40 UTC, beingnoble03 commented on src/components/EventStats/EventStats.tsx
> +import styling from './EventStats.module.css';
```suggestion
import eventStatsStyles from './EventStats.module.css';
```
Always use this type of naming while importing css.

2023-12-28 18:42 UTC, beingnoble03 requested changes
Please address the above comments. Also, upload the after and before video screenshots effects of this PR, in the PR descriptions.

2023-12-28 18:44 UTC, duplixx commented
yeah sure @beingnoble03 i'll make changes thanks for review!!

2023-12-29 16:42 UTC, beingnoble03 approved these changes
LGTM!

2023-12-29 18:22 UTC, noman2002 approved these changes

2023-12-29 18:23 UTC, merged