Fixed-Issue-#1285 Inconsistent character limit during organization cr…
PalisadoesFoundation/talawa-admin pull request #1321
Opened 2023-12-29 17:44 UTC by gauravsingh94

…eation for both name and description.

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1285 

**Did you add tests for your changes?**

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/ea0edc92-67d5-40c9-955f-190506e62e1b

**If relevant, did you update the documentation?**

**Summary**

Now we can enter only 50 character for the organization name and 100 for the organization description and location.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

2023-12-29 17:50 UTC, gauravsingh94 commented
I have Updated it

50 characters for the organization name.
200 characters for the organization description.
100 characters for the organization location.

2023-12-30 13:29 UTC, noman2002 requested changes

2023-12-30 13:29 UTC, noman2002 commented on src/screens/OrgList/OrgList.tsx
> +                  if (descriptionText.length < 100) {
Change it to 200

2023-12-30 14:02 UTC, gauravsingh94 commented on src/screens/OrgList/OrgList.tsx
> +                  if (descriptionText.length < 100) {
Done 👍.

2023-12-31 15:49 UTC, aashimawadhwa approved these changes
LGTM 👍🏼 @noman2002  can be merged

2023-12-31 15:59 UTC, rishav-jha-mech commented
LGTM

2023-12-31 16:00 UTC, rishav-jha-mech approved these changes

2023-12-31 16:50 UTC, noman2002 approved these changes

2023-12-31 16:50 UTC, merged