test: created tests for src/components/AddOn/core/AddOnStore/AddOnSto…
PalisadoesFoundation/talawa-admin pull request #1363
Opened 2024-01-03 10:05 UTC by ALOK9442

Fixes #1038 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Not required

**If relevant, did you update the documentation?**

No documentation update required

**Summary**

I added unit tests for  src/components/AddOn/core/AddOnStore/AddOnStore.tsx

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes, I have read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)

2024-01-03 11:38 UTC, ALOK9442 commented
@palisadoes 
I am new to this repo, please look into this whether any modifications are required. Your insights will be appreciated.

2024-01-03 13:38 UTC, beingnoble03 commented on src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx
> +  test('installs a plugin when "Install" button is clicked in AddOnEntry', async () => {
This test needs an expect statement.

2024-01-03 13:39 UTC, beingnoble03 requested changes
@ALOK9442 there are many tests in this PR, which need `expect` statement. Please look into it.

2024-01-06 23:35 UTC, ALOK9442 commented
I have added the expect statements, please look into this whether any modifications are required. Your insights will be appreciated.

2024-01-15 16:55 UTC, palisadoes commented
1. This needs to be closed. You are merging against `main` versus `develop`
2. Do all your edits against the latest upstream for `develop` and propose merging your PR's branch against `develop`
3. Closing

2024-01-15 16:55 UTC, closed without merging

2024-01-15 17:39 UTC, ALOK9442 commented
I tried to rebase my main with upstream/develop but facing this issue while fetching upstream
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/104527572/03fa033f-51c5-4d1c-b933-62d16eadf4a4)