Fix: issue #1380 by simplifying the modal closure mechanism in the 'Manage Features' modal.
PalisadoesFoundation/talawa-admin pull request #1393
Opened 2024-01-06 20:14 UTC by harshpreet14

**What kind of change does this PR introduce?**

This PR addresses issue #1380 by simplifying the modal closure mechanism in the 'Manage Features' modal in OrgList.tsx. 

**Changes Made:**
- Replaced the title div of the Modal with 'Modal Header', aligning it with other modals in the application for consistency.
- Removed the 'Cancel' button and retained the 'X' icon for closing the modal.
- Updated the OrgList.test.tsx file to reflect these changes by removing tests related to the 'CloseOrganizationModal' button.

**Issue Number:**
Fixes #1380 

**Did you add tests for your changes?**
-Verified that - On clicking cross button the modal should close, on clicking outside the modal the modal should close, on pressing escape key on keyboard the modal should close.
- No, there was no need for redundant tests for Modal Header. 
- Executed individual file tests using `npm run test --watchAll=false /path/to/test/file`.
- Measured code coverage for changes with `npm run test -- --collectCoverageFrom="src/screens/OrgList/*" /src/screens/OrgList/OrgList.test.tsx`.

**Snapshots/Videos:**
Before- 
<img width="960" alt="Screenshot 2024-01-06 013241" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/94c8670d-8ac5-4c9d-a41e-f768f8f4a203">
After- 
<img width="960" alt="Screenshot 2024-01-06 184946" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/3bd0fbaa-b878-4558-8967-b9e62617032f">
OrgList.test.tsx - 
<img width="769" alt="Screenshot 2024-01-06 235928" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/81662555-5d9e-493b-ae16-fd57a2571ac5">
Code coverage- 
<img width="728" alt="Screenshot 2024-01-07 003019" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/246d3660-e442-4f6d-a7c7-5a5d2cf8e1e7">

**If relevant, did you update the documentation?**
NA

**Summary**
Simplifies the modal interface, enhancing the overall user experience and reducing potential confusion.

**Does this PR introduce a breaking change?**

NA

**Other information**
If further tests are required for the specific modal in OrgList.tsx, please let me know, and I'll be more than happy to add them. Thank you for considering my contribution!

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2024-01-07 05:47 UTC, rishav-jha-mech commented on package-lock.json
> +      "engines": {
Revert any change you make to this file

2024-01-07 05:53 UTC, rishav-jha-mech commented
@harshpreet14 Remove the custom CSS from the modal buttons and make them look like the other buttons we are using (Bootstrap buttons)

Also remove all the changes made to Orglist.module.css in this PR
https://github.com/PalisadoesFoundation/talawa-admin/pull/951/files#diff-6d92acde99b887d1558bf07492bfac03d6fdffcab0f3f9b4a52a14df094dbe6c

2024-01-07 14:32 UTC, harshpreet14 commented
Hi Rishav, I have implemented the changes as suggested. The modifications include updating the buttons to Bootstrap versions, cleaning up unused CSS classes, adding new classes for specific buttons, and implementing an additional test for the 'Go to Plugin Store' button.

2024-01-16 04:57 UTC, rishav-jha-mech commented
@harshpreet14 share the updated Screenshot

2024-01-16 13:31 UTC, harshpreet14 commented
Here's the screenshot @rishav-jha-mech 
<img width="960" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/1e1595c4-ed1a-4624-9f3b-0d23bc456df0">

2024-01-17 21:36 UTC, beingnoble03 commented on src/screens/OrgList/OrgList.tsx
> +            data-testid="modalOrganizationHeader"
Rename the `data-testid`. It's already used for other modal above in the same component.

2024-01-17 21:37 UTC, beingnoble03 requested changes
@harshpreet14 please address the comment. Rest lgtm.

2024-01-21 16:11 UTC, noman2002 commented
@harshpreet14 Any update on this ?

2024-01-21 20:24 UTC, harshpreet14 commented
@noman2002 fixed the redundant test-id. 
<img width="560" alt="Screenshot 2024-01-22 014256" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/33b332e1-e679-442b-9558-7e197e3b2321">

2024-01-22 13:03 UTC, noman2002 commented
@beingnoble03 Should this be merged ?

2024-01-22 13:45 UTC, beingnoble03 commented
> @beingnoble03 Should this be merged ?

Yes

2024-01-22 15:09 UTC, merged