Feature: Allow Single Object Upload Photo/video
PalisadoesFoundation/talawa-admin pull request #1444
Opened 2024-01-17 15:35 UTC by duplixx

**What kind of change does this PR introduce?**

 Feature

**Issue Number:**

Fixes #1127 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
All the videos and snapshots are present in this pr
 #1193

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

2024-01-17 19:17 UTC, beingnoble03 commented
Please fix the failing tests.

2024-01-22 13:08 UTC, duplixx commented
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/62d71823-59ac-4e93-887d-3dfd3d52e1db)
this workflow error is not part of my pr how should i fix this @palisadoes @beingnoble03

2024-01-22 15:25 UTC, palisadoes commented
The introspection test will fail as we have added features to the API that are not yet implemented in Admin

@beingnoble03 
@noman2002 

Please review

2024-01-24 10:06 UTC, beingnoble03 commented on public/locales/en.json
> +    "addMedia": "Upload Photo or Video",
```suggestion
    "addMedia": "Upload Media",
```

2024-01-24 10:07 UTC, beingnoble03 commented on public/locales/en.json
> +    "addMedia": "Upload Photo or Video",
Add translations to other json files too.

2024-01-24 10:08 UTC, beingnoble03 commented on src/screens/OrgPost/OrgPost.tsx
> -                <Form.Label htmlFor="postvideo">{t('video')}</Form.Label>
I think you can delete `video` from `en.json` and other files too. If it's not in use anywhere else in this component/screen.

2024-01-24 10:10 UTC, beingnoble03 commented on src/screens/OrgPost/OrgPost.tsx
> -                <Form.Label htmlFor="postPhoto">{t('image')}</Form.Label>
I think you can delete `image` from `en.json` and other files too. If it's not in use anywhere else in this component/screen.

2024-01-24 10:11 UTC, beingnoble03 requested changes
@duplixx please address the comments. Rest lgtm.

2024-01-24 14:07 UTC, duplixx commented
@beingnoble03 changes done !!

2024-01-27 07:42 UTC, duplixx commented
i have done changes can we merge it @palisadoes @beingnoble03 @noman2002

2024-01-27 21:40 UTC, noman2002 approved these changes
LGTM

2024-01-27 22:27 UTC, palisadoes requested changes
Please merge with the latest upstream. 

The tests should pass now

2024-01-28 07:40 UTC, palisadoes approved these changes

2024-01-28 07:40 UTC, merged