feat: added editorconfig
PalisadoesFoundation/talawa-admin pull request #1492
Opened 2024-01-24 18:04 UTC by takshakmudgal

What kind of change does this PR introduce?

This pull request introduces a feature of an updated EditorConfig file. The EditorConfig file is a configuration file that helps maintain consistent coding styles across different editors and IDEs used in the project. By defining indentation styles, line endings, and whitespace conventions, the EditorConfig ensures that all developers working on the project follow the same coding standards.
In this update, I have refined the indentation styles and sizes specifically for TypeScript, JavaScript, JSX, and React files. The configuration enforces the use of spaces for indentation with an indent size of 2 spaces for TypeScript and JavaScript files. For JSX and React files, the same configuration is applied, ensuring a consistent coding style throughout the project.
Additionally, the EditorConfig file sets the line endings to Unix-style (LF), specifies the character encoding as UTF-8, and enforces whitespace conventions by trimming trailing whitespaces and inserting a final newline at the end of each file.
This feature contributes to code consistency, readability, and collaboration among developers by providing a standardized configuration for code formatting.

Issue Number:

Fixes #1471

Did you add tests for your changes?

No

Snapshots/Videos:

If relevant, did you update the documentation?

No

Summary

 
This pull request updates the EditorConfig file to enforce consistent coding styles and whitespace conventions across the project. It aligns with the organization's coding standards.

Does this PR introduce a breaking change?

No

Other information

None

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?

Yes

2024-01-25 01:16 UTC, Cioppolo14 commented
@noman2002  @anwersayeed Can you review this PR?

2024-01-27 21:52 UTC, noman2002 approved these changes
Looks fine.

2024-01-27 22:23 UTC, palisadoes requested changes
Please merge your code with the latest upstream. The failing tests should pass

2024-01-28 15:26 UTC, palisadoes approved these changes

2024-01-28 15:27 UTC, merged