Replace all hard coded localhosts with env constant variables
PalisadoesFoundation/talawa-admin pull request #1497
Opened 2024-01-25 15:25 UTC by NayOoLwin5

**What kind of change does this PR introduce?**

Replacement of all hard coded localhost urls in places with environment constant variables.
**Issue Number:**

Fixes #1244 

**Did you add tests for your changes?**

**Snapshots/Videos:**
<img width="1053" alt="Screenshot 2024-01-25 at 20 23 40" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/52243229/08917ce9-85d4-41b8-b8b4-1f722456ece3">

**If relevant, did you update the documentation?**

Yes

**Summary**
- With PR #1488 merged, I had to introduce new env variable `REACT_ADMIN_FRONTEND_HOST` for two test files to access host IP and port separately and wrote a prompt for it in setup
- Leaving hard coded localhost in file `/src/components/AddOn/support/services/Plugin.helper.ts` as I was informed it is outdated and no longer used

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2024-01-25 20:37 UTC, Cioppolo14 commented
@NayOoLwin5 Please fix the test application failing tests.

2024-01-25 21:28 UTC, palisadoes requested changes
1. I don't see the need to create the `REACT_ADMIN_FRONTEND_HOST` variable when relative variables would seem to be equally suitable.
2. Let us know why this is necessary
3. The replacement of `localhost` with the `BACKEND_URL` is clearly necessary.

2024-01-25 21:28 UTC, palisadoes commented on src/screens/LoginPage/LoginPage.test.tsx
> +    expect(fetch).toHaveBeenCalledWith(BACKEND_URL);
Why is this necessary for testing when we will always be testing against localhost?

2024-01-25 21:28 UTC, palisadoes commented on src/screens/UserPortal/Home/Home.test.tsx
> +  const url = REACT_APP_CUSTOM_PORT
Why can't this be a relative URL?

2024-01-25 21:28 UTC, palisadoes commented on src/screens/EventDashboard/EventDashboard.test.tsx
> +      ? `${REACT_ADMIN_FRONTEND_HOST}:${REACT_APP_CUSTOM_PORT}/event/event123`
Why can't this be a relative URL?

2024-01-26 20:40 UTC, NayOoLwin5 commented
- I checked and found out all test files have its mock responses against the localhost. Therefore, no need of dynamic env variables. Thanks for pointing them out.
- However, running tests only with relative url resulting in failures. Thus, I kept them same as it was. Please review and let me know if anything more needed to be fixed. 

@palisadoes

2024-01-26 21:11 UTC, palisadoes commented
Please fix the failing tests

2024-01-27 14:10 UTC, NayOoLwin5 commented
- I cannot reproduce the test failures on my machine even though using node version 20. 
- However, I tested the login page manually by myself and the fetch checks are working as expected with my new changes. 
- No changes to the failed test files also as I changed back to previously existing code. 

Please let me know how I can reproduce the failed tests. @palisadoes

2024-01-27 15:05 UTC, palisadoes commented
1. Scroll down in the test box
2. Click on this link
3. It is explained there

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/ac35fe2b-97a6-4568-ab6a-53bf8ebbffa3)

2024-01-27 21:12 UTC, NayOoLwin5 commented
Hi @palisadoes, the test should work fine now. The issue was removing dynamic env `BACKEND_URL` variable from the test files as the value in fetch expect the same as that is parsed in fetch in the components. Added it back and let us check the test again.

2024-01-27 21:44 UTC, palisadoes approved these changes

2024-01-27 21:44 UTC, merged