feat: lint files which are changed with strict rules
PalisadoesFoundation/talawa-admin pull request #1523
Opened 2024-01-31 10:02 UTC by devsargam

**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1427

**Did you add tests for your changes?**
No

**Summary**
Improved gh workflow to only check those files which are changed to lint

**Does this PR introduce a breaking change?**
Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2024-01-31 16:02 UTC, devsargam commented
This pr needs to change the following files
- `.eslintrc.json`
- `.github/workflows/pull-requests.yml`

so, I'd request a maintainer to allow `unauthorized file change` in this pr

2024-02-01 05:17 UTC, devsargam commented
hey @palisadoes  can you please look into this?

2024-02-01 12:25 UTC, Cioppolo14 commented
@devsargam We are aware of an issue with UpdateUserInput, but for now can you update your schema file to pass the introspection test.

2024-02-01 12:27 UTC, Cioppolo14 commented
@EshaanAgg @sumitra19jha Can you review this PR?

2024-02-01 12:28 UTC, devsargam commented
> @devsargam We are aware of an issue with UpdateUserInput, but for now can you update your schema file to pass the introspection test. 

Should I edit the schema file myself or is there a pr ongoing for that?

2024-02-01 12:32 UTC, Cioppolo14 commented
> > @devsargam We are aware of an issue with UpdateUserInput, but for now can you update your schema file to pass the introspection test.
> 
> Should I edit the schema file myself or is there a pr ongoing for that?

The fix was merged last night, so I think you just need to update your files.

2024-02-01 12:48 UTC, Cioppolo14 commented
@devsargam The recent merge will fix some of the introspection errors, but not all, you just need to manually add UpdateUserInput in schema and then it'll pass. I need to investigate further into this part.

2024-02-02 03:24 UTC, SiddheshKukade requested changes

2024-02-02 03:24 UTC, SiddheshKukade commented on src/GraphQl/Mutations/mutations.ts
Why did you deleted the fields ?

2024-02-02 03:58 UTC, palisadoes commented on src/GraphQl/Mutations/mutations.ts
1. You need to restore this and get the tests to pass in a valid way.
1. The fact that tests pass doesn't mean that they properly verify functionality.

2024-02-03 20:00 UTC, devsargam commented on src/GraphQl/Mutations/mutations.ts
as mentioned in this https://github.com/PalisadoesFoundation/talawa-admin/pull/1525#discussion_r1475525268 should I follow the same statement or???

2024-02-03 20:35 UTC, palisadoes commented on src/GraphQl/Mutations/mutations.ts
1. There have been many merged PRs since this one was opened. All their tests passed and the lines that you removed are maintained.
2. Please merge with the latest upstream, and fix your tests to comply with the code base. You are removing functionality that must be maintained

2024-02-04 19:05 UTC, devsargam commented
Hey, mentors can someone help with this pr?
- First test is failing because I have changed files like .eslint and .github/workflows/* 
- Second test is failing because of graphql schema conflict between our current repo and the api repo
- Third test is failing of some unknown linting reasons

How should I proceed can someone help?

2024-02-04 19:30 UTC, palisadoes commented
1. @NamitBhutani could you provide some guidance? 
2. You worked on something similar for the API PR process

2024-02-11 13:54 UTC, palisadoes commented
Are you still working on this?

2024-02-12 15:18 UTC, devsargam commented
Yes. I am facing errors on the graphql test

2024-02-15 06:15 UTC, devsargam commented
Hye, @palisadoes sir, can I close this pr and open another one. I want to try a bit different approach & this pr also has merge conflicts

2024-02-15 12:12 UTC, palisadoes commented
No. 

1. Merge conflicts are a regular part of code development.
1. We lose track of the reviews history when you close the PR
1. The new approach will update the files to review when pushed you the PR

Create a new local branch with your new approach. Merge it into the branch for this PR when ready.

2024-02-17 19:42 UTC, palisadoes commented
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

2024-02-18 16:05 UTC, palisadoes commented
Can you do the changes as suggested, or can you find no other way of solving the issue without a new PR?

2024-02-18 17:18 UTC, devsargam commented
Sir, I tried doing it locally but it's pretty difficult as my branch is behind the latest develop by a lot. So, if possible can I release a new pr?

2024-02-18 18:29 UTC, closed without merging