User - People UI - Redesign
PalisadoesFoundation/talawa-admin pull request #1654
Opened 2024-03-02 20:10 UTC by pranshugupta54

**What kind of change does this PR introduce?**

User -> People -> Redesigning

**Issue Number:**

Fixes #1607 

**Did you add tests for your changes?**

**Snapshots/Videos:**

<img width="1439" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/a43c6fc7-b676-4fd9-ab9b-ccaeb510e3e4">

**Other information**

The left side panel (according to Figma) should be fixed in another issue to match the design.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2024-03-02 22:36 UTC, pranshugupta54 commented
Not sure why `Check for eslint-disable` is failing, because this PR doesn't even touch OrganizationPeople folder
<img width="1019" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/f402eba0-5bc7-49f2-98ef-93042d576ef2">

2024-03-02 22:44 UTC, pranshugupta54 commented
Not sure why `Runs Introspection on the GitHub talawa-api repo on the schema.graphql file` fails. I've only added `userType` for `ORGANIZATIONS_MEMBER_CONNECTION_LIST` to display roles for the user on People page. Github Action shows some irrelevant error.

<img width="864" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/8522b7fa-608e-426d-a5b9-a2fbd0b9d764">

2024-03-02 23:09 UTC, pranshugupta54 commented
Added `userType` in tests

2024-03-03 16:51 UTC, palisadoes commented
Please remove the lint ignore statement so that we can review
```
talawa-admin/src/screens/OrganizationPeople/OrganizationPeople.tsx
```

2024-03-03 16:53 UTC, palisadoes commented
Fix the failing tests so that we can review

2024-03-03 17:06 UTC, pranshugupta54 commented
Hey @palisadoes, the eslint-disable directive is already present in the original repository. This file is not associated with the current pull request. It was included in a previous pull request, PR #1568.

2024-03-03 17:09 UTC, pranshugupta54 commented
I believe the GitHub Action failure for all upcoming PRs is being caused by a previously merged PR that included the eslint-disable directive.

2024-03-03 17:14 UTC, palisadoes commented
1. Please fix it. 
2. This is a newly implemented test, there should be a few that we missed

2024-03-04 01:36 UTC, Cioppolo14 commented
@Tajcore @noman2002 Can you review this PR?

2024-03-04 06:08 UTC, noman2002 requested changes

2024-03-04 06:08 UTC, noman2002 commented on public/locales/en.json
>      "nothingToShow": "Nothing to show here.",
Please update this in all languages.

2024-03-04 06:21 UTC, pranshugupta54 commented on public/locales/en.json
>      "nothingToShow": "Nothing to show here.",
fixed

2024-03-04 12:45 UTC, Tajcore commented
Please update branch and resolve any merge conflicts that may arise

2024-03-05 03:19 UTC, aashimawadhwa commented
Can you relove pagination? @pranshugupta54  we are suing infinite scroll across talawa .

2024-03-09 12:16 UTC, pranshugupta54 commented
> Can you remove pagination? @pranshugupta54 we are using infinite scroll across talawa .

Hey @aashimawadhwa, can you please clarify over this. I see pagination everywhere across Talawa. Can you refer some infinite scroll? Do you want me to list all the users at once or do you want them to load depending on user scroll event? (In my opinion, pagination would be a better choice here. Infinite scroll is preferred when there is not definite end point or count, like scrolling feed section with endless posts. But user list is a finite number so pagination should be preferred.)

2024-03-09 16:21 UTC, pranshugupta54 commented
A recent merge made like 100+ changes to file, not sure whats the issue. Just made a new PR for this #1694

2024-03-09 16:21 UTC, closed without merging