Fixed Organization Post Card
PalisadoesFoundation/talawa-admin pull request #1727
Opened 2024-03-15 03:29 UTC by Shreyas2309

**What kind of change does this PR introduce?**

Bug Fixed Feature added

**Issue Number:**

Fixes #1713 

**Did you add tests for your changes?**

N/A

**Snapshots/Videos:**

https://vimeo.com/923604484?share=copy

**If relevant, did you update the documentation?**

N/A

**Summary**

1. What was the problem ?

   The DOMException: The play() request was interrupted by a call to pause() error typically occurs in web development when 
   there's an attempt to play media (like audio or video) that gets interrupted by a call to pause the media playback. This can 
   happen due to various reasons, such as asynchronous events or user interactions triggering both play and pause commands 
   simultaneously.

2. Motivation for solving the problem .

    The motivation behind solving this issue through a pull request is to enhance the robustness and reliability of web 
    applications, particularly those involving media playback. By addressing this error, developers aim to provide a smoother and 
    more seamless user experience by preventing unexpected interruptions in media playback. 

3. After solving the issue....
   
   By resolving this issue, developers can ensure that media playback behaves predictably and as intended, reducing the 
   likelihood of errors mentioned and improving the overall quality of the user experience. #1713 

**Does this PR introduce a breaking change?**

N/A

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2024-03-15 04:29 UTC, dhanagopu commented
@anwersayeed @beingnoble03 Can you review this PR?

2024-03-15 04:33 UTC, dhanagopu commented
@Shreyas2309 Please fix the conflicting files.

2024-03-15 06:40 UTC, Shreyas2309 commented
I think I have Resolved the conflicts. 
Please review the PR.

2024-03-16 05:34 UTC, beingnoble03 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +      console.log('IIIII');
remove debug statement?

2024-03-16 05:39 UTC, beingnoble03 requested changes
there are some lint errors, can you please fix those?

2024-03-16 05:39 UTC, beingnoble03 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +      console.log('IIIII');
remove debug statement?

2024-03-16 05:39 UTC, beingnoble03 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +    // setModalVisible(false);
remove comments.

2024-03-16 05:39 UTC, beingnoble03 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +          // setModalVisible(true);
remove comment

2024-03-16 05:39 UTC, beingnoble03 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +                }}
seems unnecessary change.

2024-03-16 05:39 UTC, beingnoble03 commented on package-lock.json
i don't think we need package-lock and package.json changes here?

2024-03-16 05:39 UTC, beingnoble03 commented on package.json
i don't think we need package-lock and package.json changes here?

2024-03-16 05:47 UTC, akhilender-bongirwar commented
![checknotrunning](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/213a8dfe-8c95-471a-ab28-f8db5d41801a)


@beingnoble03, I think the check `PR Workflow / Performs linting, formatting, type-checking (pull_request) ` is not working fine as there are no files with changes more than 600 lines in this PR.

2024-03-16 05:55 UTC, Shreyas2309 commented
I have fixed the linting errors . Can you please review it.

2024-03-16 06:35 UTC, Shreyas2309 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +      console.log('IIIII');
removed it

2024-03-16 06:35 UTC, Shreyas2309 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +    // setModalVisible(false);
removed it

2024-03-16 06:36 UTC, Shreyas2309 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +          // setModalVisible(true);
removed it

2024-03-16 06:37 UTC, Shreyas2309 commented on src/components/OrgPostCard/OrgPostCard.tsx
> +                }}
fixed it

2024-03-16 06:38 UTC, Shreyas2309 commented on package-lock.json
removed the unnecessary changes

2024-03-16 06:38 UTC, Shreyas2309 commented on package.json
removed the unnecessary changes

2024-03-17 00:06 UTC, palisadoes commented
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

2024-03-22 16:54 UTC, palisadoes commented
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-23 15:41 UTC, palisadoes commented
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-24 11:59 UTC, Cioppolo14 commented
@Shreyas2309 Please fix the failing tests and conflicting files.

2024-03-30 22:41 UTC, closed without merging

2024-03-30 22:41 UTC, palisadoes commented
Closing as abandoned