Feat/pledges
PalisadoesFoundation/talawa-admin pull request #1732
Opened 2024-03-16 18:44 UTC by AVtheking

**What kind of change does this PR introduce?**
This PR add support for Campaign pledges

**Issue Number:**

Fixes #1623 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/132201033/387d37b7-ae23-46e0-9bb3-db17c924c616

2024-03-16 22:45 UTC, Cioppolo14 commented
@AVtheking  Please fix the failing code cov tests.

2024-03-17 09:26 UTC, AVtheking commented
@Cioppolo14  fixed the codecov error please assign reviewers

2024-03-20 10:17 UTC, AVtheking commented
@Cioppolo14  @palisadoes  please assign reviews so that it can be reviewed.

2024-03-20 12:02 UTC, Cioppolo14 commented
@anwersayeed @tasneemkoushar Can you review this PR?

2024-03-22 16:54 UTC, palisadoes commented
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-23 15:40 UTC, palisadoes commented
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-23 19:55 UTC, palisadoes requested changes
Minor fix. There is a re-import, but we need to add it to linting too.

2024-03-23 19:55 UTC, palisadoes commented on src/App.tsx
> +import React from 'react';
Fix this duplicate identifier error. Add the linting test to the eslint file:
- https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.eslintrc.json

2024-03-23 19:57 UTC, palisadoes commented
Please fix the failing test

2024-03-24 07:14 UTC, palisadoes commented
Please fix the formatting

2024-03-24 09:40 UTC, AVtheking commented
@palisadoes  all tests are passing now

2024-03-24 12:01 UTC, Cioppolo14 commented
@AVtheking The test application check is not passing.

2024-03-24 12:43 UTC, AVtheking commented
@Cioppolo14  @palisadoes now all tests are passing.

2024-03-24 15:14 UTC, palisadoes approved these changes

2024-03-24 15:14 UTC, merged