Merging develop-userTypeFix in develop
PalisadoesFoundation/talawa-admin pull request #1761
Opened 2024-03-22 22:29 UTC by AVtheking

What kind of change does this PR introduce?

Feature

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Did you add tests for your changes?

Yes

Summary

Merging the develop-userTypeFix branch in develop.

Does this PR introduce a breaking change?
Yes

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

Yes

2024-03-22 22:32 UTC, palisadoes commented
@Avtheking I'm going to close this PR. Use another source branch tests are going to fail

2024-03-22 22:44 UTC, pranshugupta54 requested changes

2024-03-22 22:44 UTC, pranshugupta54 commented on src/screens/OrgList/OrgList.tsx
> +  function openDialogModal(redirectOrgId: string) {
Make the function `void` and remove eslint-disable

2024-03-22 22:44 UTC, pranshugupta54 commented on src/screens/OrgList/OrgList.tsx
> +  function closeDialogModal() {
Make the function `void` and remove eslint-disable

2024-03-22 22:44 UTC, pranshugupta54 commented on src/screens/OrgList/OrgList.tsx
> +        // eslint-disable-next-line
Remove eslint and wrap the complete div in `<> </>`

2024-03-22 22:44 UTC, pranshugupta54 commented on src/screens/Users/Users.tsx
> +        // eslint-disable-next-line react/jsx-indent
Remove disable and wrap complete in `<> </>`

2024-03-22 22:50 UTC, palisadoes commented
@pranshugupta54 We are collaborating on this PR. You can ask @AVtheking to be a contributor to his repo and you can apply updates if you are interested.

2024-03-22 22:51 UTC, palisadoes commented
@pranshugupta54 You can accept the invitation. It should be in your inbox

2024-03-22 23:40 UTC, palisadoes commented
@varshith257 It's failing

- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/8397580202/job/23001165157?pr=1761
- It looks like it's only one file at fault.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/29fa7db4-982d-4194-b34c-ab1040393633)

2024-03-22 23:58 UTC, palisadoes commented
@varshith257 Please fix the linting.

2024-03-23 07:26 UTC, varshith257 approved these changes
LGTM
Except low test coverage

2024-03-23 07:55 UTC, pranshugupta54 commented
For MemberDetail page, I already have the re-designed page with 100% coverage. We can merge that first, currently this file has very bad coverage so instead of fixing it for old design we can use the new one.
Ref: #1667

2024-03-23 08:04 UTC, varshith257 commented
@pranshugupta54 Okay, Thanks

2024-03-23 11:37 UTC, palisadoes commented
@pranshugupta54 

1. We have to approve the GitHub action because you've never merged a PR before. This is going to be time consuming and cause delays.
2. Can you create a trivial PR in Admin that I can merge so that I don't have to approve subsequent workflows for you? For example add a space to a file

2024-03-23 15:30 UTC, merged