Redesign of Donations Page
PalisadoesFoundation/talawa-admin pull request #1846
Opened 2024-03-29 19:16 UTC by git-init-priyanshu

**What kind of change does this PR introduce?**
UI redesign.

**Issue Number:**
Fixes #1513

**Did you add tests for your changes?**
Not yet

**Snapshots/Videos:**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/79cd7f06-1dbb-4a91-bd66-eaed47a28e50)

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
yes

2024-03-29 19:27 UTC, git-init-priyanshu commented
Hey @aashimawadhwa Can you please clarify a few things:
1. What should be included in the image section of the donation card?
2. How will the search function operate?

2024-03-30 00:35 UTC, Cioppolo14 commented
@git-init-priyanshu Please fix the failing checks and add tests as needed.

2024-04-02 11:59 UTC, palisadoes requested changes
Restore all linting

2024-04-02 11:59 UTC, palisadoes commented on .eslintrc.json
> +    "@typescript-eslint/no-non-null-asserted-optional-chain": "off",
Restore all linting

2024-04-03 19:52 UTC, palisadoes approved these changes

2024-04-03 19:52 UTC, merged