Bug Report: User unable to join Organizations error solved
PalisadoesFoundation/talawa-admin pull request #1875
Opened 2024-04-04 15:05 UTC by gautam-divyanshu

**What kind of change does this PR introduce?**
User will able to join the organization.

**Issue Number:**

Fixes #1849 

**Did you add tests for your changes?**

**Snapshots/Videos:**
![Screenshot from 2024-04-04 20-14-24](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/10b30df2-0b64-42fa-90ab-64c4aa251e93)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

2024-04-04 15:11 UTC, pranshugupta54 commented on src/screens/UserPortal/Organizations/Organizations.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
don't disable eslint and fix them

2024-04-04 15:13 UTC, gautam-divyanshu commented on src/screens/UserPortal/Organizations/Organizations.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Ok

2024-04-04 15:14 UTC, pranshugupta54 commented on src/screens/UserPortal/Organizations/Organizations.tsx
>    const handleSearchByEnter = (e: any): void => {
Try using 
```ts
const handleSearchByEnter = (e: React.KeyboardEvent<HTMLInputElement>): void => {
  if (e.key === 'Enter') {
    const { value } = e.currentTarget;
    handleSearch(value);
  }
};
```

2024-04-04 15:22 UTC, palisadoes requested changes
Add a test for the bug. We don't want this to happen again.

2024-04-04 18:21 UTC, gautam-divyanshu commented
@palisadoes currently there is no page for request handling in Admin portal 

[Screencast from 2024-04-04 23-47-03.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/780d5e73-ddd7-42c3-9b2a-557956096e4e)

2024-04-04 18:23 UTC, gautam-divyanshu commented
@palisadoes Should I cover that issue in my issue?

2024-04-04 18:31 UTC, pranshugupta54 commented
@gautam-divyanshu, it's there before selecting an Org. (If there should be an improvement in it, then please take it separately to avoid a very long PR of 2 different issue types)
<img width="807" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/714fc8fe-7552-4c45-823b-8348b2a2fcf8">

2024-04-04 18:39 UTC, gautam-divyanshu commented
Oh, the problem is that I was logged in as a superadmin, and when I try to access /requests, the Request page does not load.

2024-04-04 20:22 UTC, palisadoes commented
1. Requests should be handled at the Admin level.
2. The tab needs to be moved from SuperAdmin.
3. Only Organization specific requests should be visible in the Admin panel.
4. This should be covered in the official Figma design

2024-04-05 04:09 UTC, gautam-divyanshu commented
@palisadoes  ok, I will remove the request button from superAdminScreen

2024-04-05 04:20 UTC, pranshugupta54 commented
@gautam-divyanshu, I've made a separate issue for it. We should not mix independent issues of user portal and admin portal in one PR

2024-04-05 04:40 UTC, gautam-divyanshu commented
> @gautam-divyanshu, I've made a separate issue for it. We should not mix independent issues of user portal and admin portal in one PR

I have updated the code, it requires just minor issues. 
@palisadoes you should suggest what should be done

2024-04-05 11:19 UTC, palisadoes commented
Don't change the original scope of this PR.

The other issue can be addressed later.

2024-04-05 16:36 UTC, gautam-divyanshu commented
[Screencast from 2024-04-05 21-42-23.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/fade8b4a-0724-4433-b6b2-afaa7e7c2767)

@palisadoes We can close this issue , #1874
I made changes for that in this pr.

2024-04-05 16:54 UTC, palisadoes commented
Please fix the linting & tests

2024-04-05 17:06 UTC, gautam-divyanshu commented
@palisadoes Please review

2024-04-05 17:07 UTC, gautam-divyanshu commented
@palisadoes  And can we disable this workflow approval process, just to get things fast

2024-04-05 21:33 UTC, palisadoes commented
1. The approvals are only required for your very first PR in a repo. The easiest way is to create another PR before this one so that this one won't require any more approvals.
2. Do a simple PR against the same issue. A minor change in INSTALLATION.md, like add a space. When that is merged, the problem with this PR will go away

2024-04-06 09:47 UTC, gautam-divyanshu commented
@palisadoes  please approve

2024-04-06 13:49 UTC, palisadoes commented
Subsequent commits should automatically trigger the GitHub action's

2024-04-06 13:53 UTC, gautam-divyanshu commented
Then what might be use?

2024-04-06 13:57 UTC, palisadoes commented
Please fix the failing tests

2024-04-06 13:58 UTC, gautam-divyanshu commented
@palisadoes these test cases were failing even before my pr

2024-04-06 14:02 UTC, palisadoes commented
This is the most recently merged PR. All its tests passed. Please merge with the latest upstream then verify

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1878

2024-04-06 14:06 UTC, palisadoes requested changes
Please get the test code coverage of the patch higher. It's only 11%

2024-04-06 14:09 UTC, gautam-divyanshu commented
@palisadoes  I will, but currently I will not be able to because of health issues.

2024-04-06 14:13 UTC, pranshugupta54 commented
Test is failing in un-changed files bcuz you changed Query which is indirectly affecting other files

2024-04-06 14:48 UTC, palisadoes approved these changes

2024-04-06 14:50 UTC, palisadoes commented
@gautam-divyanshu 

My 11% code coverage request was for another PR. I used the mobile app and I've noticed that it has a bug where it sometimes posts comments in the previously viewed PR especially after reviewing a lot in sequence.

Now I can't dismiss it.

2024-04-06 14:54 UTC, gautam-divyanshu commented
@palisadoes what should I do?

2024-04-06 15:03 UTC, palisadoes commented
See comment 

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1875#issuecomment-2041101097

2024-04-11 03:53 UTC, pranshugupta54 commented
@gautam-divyanshu, any updates? Are you facing some issue? This is a major issue which stops User Portal from main functionality.

2024-04-11 04:08 UTC, gautam-divyanshu commented
> @gautam-divyanshu, any updates? Are you facing some issue? This is a major issue which stops User Portal from main functionality.

@pranshugupta54 I will make the updates soon, I was inactive because of health issues

2024-04-11 04:09 UTC, pranshugupta54 commented
Ohk no problem, take care! If you need help, feel free to connect on Slack.

2024-04-11 05:03 UTC, gautam-divyanshu commented
@palisadoes  Please review

2024-04-11 05:05 UTC, pranshugupta54 commented
Why didn't we get an error on `src/components/UserPortal/OrganizationCard/OrganizationCard.test.tsx` which checks "Join Now" button 🤔

2024-04-11 05:12 UTC, gautam-divyanshu commented
> mponents/UserPortal/OrganizationCard/OrganizationCa

This check is performed using the `expect(screen.getByTestId('joinBtn')).toBeInTheDocument()`

2024-04-11 05:16 UTC, pranshugupta54 commented
Yeah but how did it pass when there was no button on screen??

2024-04-11 05:42 UTC, gautam-divyanshu commented
> Yeah but how did it pass when there was no button on screen??

The tests passed because we focused on the underlying functionality triggered by a mocked element (button with data-testid) rather than its physical presence on the screen.

2024-04-11 05:44 UTC, pranshugupta54 commented
data-testid won't be there if button doesn't render

2024-04-11 05:48 UTC, gautam-divyanshu commented
> data-testid won't be there if button doesn't render

If the "Join Now" button is not rendered due to incorrect conditions or missing data, the screen.getByTestId('joinBtn') call will fail to find the button, and the test will also fail.

2024-04-11 05:52 UTC, pranshugupta54 commented
"Join Now" didn't render thats why we made an issue and this is the PR but the test was passing earlier too, means there is some issue with test so you should fix it in this PR itself to completely solve this and not get this issue in future again.

2024-04-11 06:08 UTC, gautam-divyanshu commented
> "Join Now" didn't render thats why we made an issue and this is the PR but the test was passing earlier too, means there is some issue with test so you should fix it in this PR itself to completely solve this and not get this issue in future again.

I have added a test

2024-04-11 07:19 UTC, gautam-divyanshu commented
@palisadoes  Please review

2024-04-12 00:48 UTC, palisadoes approved these changes

2024-04-12 00:48 UTC, merged