Chore/organization people UI changes
PalisadoesFoundation/talawa-admin pull request #2358
Opened 2024-10-27 04:02 UTC by AVtheking

**What kind of change does this PR introduce?**

refactoring color schemes for color blind people

**Issue Number:**

Fixes #
**Does this PR introduce a breaking change?**

NO

2024-10-27 19:03 UTC, palisadoes commented
Please fix the conflicting files

2024-10-27 19:05 UTC, palisadoes requested changes
Please explain the changes to the `pre-commit` file

2024-10-27 19:05 UTC, palisadoes commented on .husky/pre-commit
> +# npm run typecheck
Why was this done? I

2024-10-28 02:14 UTC, AVtheking commented on .husky/pre-commit
> +# npm run typecheck
it was by mistake reverted it.

2024-10-30 20:30 UTC, palisadoes commented
Please make sure coderabbit approves your changes

2024-10-30 21:19 UTC, palisadoes commented
Can you start creating a single CSS file with this PR? Then you can update that file for all subsequent color scheme design changes.

It will help greatly in standardizing the look and feel

2024-11-06 15:06 UTC, palisadoes commented
Please fix the failing tests

2024-11-06 16:30 UTC, palisadoes approved these changes

2024-11-06 16:30 UTC, merged