fixed:#1887 Event and Holiday Calendar View
PalisadoesFoundation/talawa-admin pull request #2534
Opened 2024-12-01 07:58 UTC by gurramkarthiknetha

This feature displays an interactive calendar view for tracking events and holidays. The calendar highlights holidays and user/organization-created events for the selected month, with color-coded markers for easy identification

**What kind of change does this PR introduce?**
This PR introduces a new feature for displaying an interactive event calendar with a list of holidays and user/organization-created events.

**Issue Number:**

Fixes #1887 

**Did you add tests for your changes?**
Yes, unit tests have been added to ensure the functionality works as expected.

**Snapshots/Videos:**
Snapshots and a short demonstration video showcasing the feature have been attached for better understanding.
<img width="1657" alt="image" src="https://github.com/user-attachments/assets/842afe66-6491-4e63-b2cb-2e15f238335a">

**If relevant, did you update the documentation?**
Yes, the relevant sections in the [Talawa-Docs](https://github.com/PalisadoesFoundation/talawa-docs) have been updated to include details about the new feature.
**Summary**

This feature addresses the need for a more user-friendly and comprehensive event calendar.

Problem: The existing calendar lacked the ability to display a list of holidays and events in an organized manner.
Solution:
A list of holidays and events is now displayed below the calendar.
Color-coding has been implemented to distinguish between holidays and events for improved usability.
The UI aligns with the Figma design shared by the team.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Other information**

The Figma design used for this implementation can be found [here](https://www.figma.com/file/dTGr5CnGHvkilU5nwnRXg2/Talawa-Admin-UI-Redesign?type=design&node-id=910-355&mode=design&t=EVDV5SZ2cKnOAc2R-0).
This PR follows the project’s contribution guidelines and is submitted against the develop branch, as recommended.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2024-12-01 11:49 UTC, palisadoes requested changes
Your PR has too many unnecessary files that don’t relate to your issue. You can from the PR by running the commands below from the root directory of the repository

git add -u
git reset HEAD path/to/file
git commit

Please apply these changes to the files indicated.

2024-12-01 11:49 UTC, palisadoes commented on .husky/pre-commit
Your PR has too many unnecessary files that don’t relate to your issue. You can from the PR by running the commands below from the root directory of the repository

git add -u
git reset HEAD path/to/file
git commit

Please apply these changes to this file.

2024-12-01 11:49 UTC, palisadoes commented on package.json
> +    "jest-preview": "^0.2.3",
Your PR has too many unnecessary files that don’t relate to your issue. You can from the PR by running the commands below from the root directory of the repository

git add -u
git reset HEAD path/to/file
git commit

Please apply these changes to this file.

2024-12-01 11:49 UTC, palisadoes commented on tsconfig.json
> +    "types": ["vite/client", "vite-plugin-svgr/client", "node", "vitest"],
Your PR has too many unnecessary files that don’t relate to your issue. You can from the PR by running the commands below from the root directory of the repository

git add -u
git reset HEAD path/to/file
git commit

Please apply these changes to this file.

2024-12-01 11:50 UTC, palisadoes commented
Make sure CodeRabbit.ai approves your work.

2024-12-03 03:12 UTC, palisadoes requested changes
1. These are the only 2 files that must be updated in your PR.  Please exclude the others using the methodology I mentioned.
2. Also merge your code with the latest upstream/develop-postgres branch. You seem to be reverting recent changes

![image](https://github.com/user-attachments/assets/b4588d6d-cf66-41a3-8e9c-0e7ca0da8ecb)

2024-12-03 12:57 UTC, gurramkarthiknetha commented
> 1. These are the only 2 files that must be updated in your PR.  Please exclude the others using the methodology I mentioned.
> 2. Also merge your code with the latest upstream/develop-postgres branch. You seem to be reverting recent changes
> 
> ![image](https://private-user-images.githubusercontent.com/16875803/391795216-b4588d6d-cf66-41a3-8e9c-0e7ca0da8ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzA4NjgsIm5iZiI6MTczMzIzMDU2OCwicGF0aCI6Ii8xNjg3NTgwMy8zOTE3OTUyMTYtYjQ1ODhkNmQtY2Y2Ni00MWEzLThlOWMtMGU3Y2EwZGE4ZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEyNTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkY2MwZDkwYjkwYzQ1MjVmNTdhMmEzNDZkNjliZTU2YWRlYmYyNGM3YzEyOTdiZGFmYTE2ZmY2MmJhZDFhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h67V-NGPuWIl3pRW0Eykd2zyvuG6c7sXROLXCK9vU1E)

ok

2024-12-03 16:32 UTC, palisadoes commented
1. PTAL. This cannot be reviewed by our reviewers. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2534#issuecomment-2509622160
1. Please fix the excess number of files submitted too

2024-12-04 16:42 UTC, closed without merging

2024-12-04 16:42 UTC, palisadoes commented
1. This has to be closed. 
2. You now only have the unnecessary files in the PR.
3. Please try again when you are ready