Changed the Readme.md
PalisadoesFoundation/talawa-admin pull request #26
Opened 2021-05-01 17:51 UTC by yasharth291

**What kind of change does this PR introduce?**

documentation bugfix in the readme section of the readme

**Other information**

Fixes #25

2021-05-01 17:52 UTC, yasharth291 commented
@palisadoes  @DangaRanga  please sir review it

2021-05-02 20:54 UTC, DangaRanga requested changes

2021-05-02 20:54 UTC, DangaRanga commented on README.md
> +- Want to contribute? Look at [CONTRIBUTING.md][https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md] to get started.
Remember the syntax for a hyperlink in markdown is

`[LinkTitle](URL)`

e.g) `[CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)`

gives

[CONTRIBUTING.md](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)

2021-05-02 20:55 UTC, yasharth291 commented
@DangaRanga changed sir

2021-05-02 20:56 UTC, DangaRanga approved these changes

2021-05-02 20:56 UTC, merged