fix: post not being updated [Fixes: #464]
PalisadoesFoundation/talawa-admin pull request #466
Opened 2023-02-11 10:23 UTC by anshgoyalevil

**What kind of change does this PR introduce?**
The post was not being updated inside the Talawa-Admin. Now, it is working fine.

**Issue Number:**

Fixes #464 

**Did you add tests for your changes?**
Not Required

**Snapshots/Videos:**
![image](https://user-images.githubusercontent.com/94157520/218252898-35ae0b31-397b-4362-a8bf-123e2640e62c.png)
![image](https://user-images.githubusercontent.com/94157520/218252916-300866df-cdc4-4f43-9e42-38e774f50981.png)

**If relevant, did you update the documentation?**
Not Required

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2023-02-11 13:20 UTC, palisadoes requested changes
Please update the test for this so that it doesn't happen again

2023-02-11 13:30 UTC, anshgoyalevil commented
> Please update the test for this so that it doesn't happen again

Yes, the updatePost.ts file was not there, and neither there was the Mutation available for updatePost.

I created the updatePost.ts and its corresponding test file i.e., updatePost.spec.ts

2023-02-12 19:04 UTC, noman2002 approved these changes

2023-02-13 05:37 UTC, Kevoniat approved these changes

2023-02-13 12:38 UTC, palisadoes approved these changes

2023-02-13 12:38 UTC, merged