Display and choose Organisation image
PalisadoesFoundation/talawa-admin pull request #512
Opened 2023-02-26 11:04 UTC by rishav-jha-mech

**What kind of change does this PR introduce?**
Bug fix

**Issue Number:**

Fixes #477

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
## When image exists
![Organisation List](https://user-images.githubusercontent.com/76212518/221405826-f420cddf-7e26-4168-a64a-cad418dd02f2.png)
![Organisation dashboard](https://user-images.githubusercontent.com/76212518/221405831-b5401133-9d0a-416f-aed1-601f0e1c3622.png)
## When image does not exist
![Talawa Dashboard - Google Chrome 26-02-2023 16_34_02](https://user-images.githubusercontent.com/76212518/221406619-c41a81cd-8c80-467f-81fc-a1b413f3b3fa.png)

**If relevant, did you update the documentation?**

Not required.

**Summary**
This change will ensure that Organisation image is visible at different screens, and when organisation does not have an image a placeholder image will be shown in its place.

**Does this PR introduce a breaking change?**
No

**Other information**

1. This thing was functional till yesterday, but now the images are not being saved in the backend and there's an empty folder.
2. The backend is sending a relative url path like `image/{fileName}` while it was still working, now since the server is running on different url, we have to convert this to absolute url. And now we have two options
- Frontend Way: where we have to add a backend url in the .env file, and use it throughout the application (Just as we do for graphql), by setting the image source to be `{backendurl+ props.image}`.
- Since the database stores the path to the image, when running a Query we'll use a helper function which will convert all the relative image paths to absolute image paths, (I'll create a utility for it in talawa-api).

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-02-26 18:24 UTC, noman2002 requested changes
Why the coverage has gone down ? Get is back to 100% for organizationDashboard.ts

2023-02-26 18:50 UTC, rishav-jha-mech commented
@noman2002 I'm working on it, writing the tests, please give me sometime.

2023-02-26 18:53 UTC, noman2002 commented
> @noman2002 I'm working on it, writing the tests, please give me sometime.

Sure

2023-03-01 19:41 UTC, noman2002 approved these changes

2023-03-01 21:54 UTC, palisadoes approved these changes

2023-03-01 21:54 UTC, merged