fix on Register button to add a plugin doesn't work #553
PalisadoesFoundation/talawa-admin pull request #590
Opened 2023-03-09 09:57 UTC by chiinelo

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

2023-03-09 12:48 UTC, palisadoes commented
Please fill in the template for the pull request as completely as you can. I greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

2023-03-09 12:48 UTC, palisadoes requested changes
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. I greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

2023-03-10 08:01 UTC, chiinelo commented
hi @palisadoes this is ready for a review

2023-03-10 13:07 UTC, jadeharr commented
@chiinelo The code coverage in the Codecov report has decreased. Please fix your code so that the level of coverage is at least maintained

2023-03-11 19:13 UTC, closed without merging

2023-03-11 19:14 UTC, noman2002 requested changes
The newly added plugin is pushed to the end. Please sort it in a way so that it should be displayed at the top.