Fix to the issue #585
PalisadoesFoundation/talawa-admin pull request #607
Opened 2023-03-09 14:37 UTC by arushi2715

**What kind of change does this PR introduce?**

This PR introduces a bug fix.

**Issue Number:**

Fixes # 585

**Snapshots/Videos:**

![image](https://user-images.githubusercontent.com/78142604/224057199-377e3024-34ce-4181-ba24-c882b87cc2e1.png)

**If relevant, did you update the documentation?**

No

**Summary**

Earlier, the password field showed a warning even when it satisfied the criteria which leaves a sense of confusion for the user. Fixing this gives a clear idea to the user.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes #585

2023-03-09 14:45 UTC, arushi2715 commented
Hey @palisadoes can you look into this once again please?

2023-03-09 15:06 UTC, palisadoes commented
After reviewing this again, the text is informative to a new user registering. Removing it would create more chances for a poor user experience. 

Closing. Don't be discouraged. Please search for other areas of improvement.

2023-03-09 15:10 UTC, arushi2715 commented
@palisadoes the issue with this is that even if the password satisfies the criteria i.e. is 8 character long even then it shows the check message. What I wanted to do here was to remove the text "password should be 8 character long" if the password entered by user is 8 character long.

2023-03-09 16:03 UTC, arushi2715 commented
@palisadoes @xoldyckk can you look into this?

2023-03-10 11:45 UTC, xoldyckk commented
@palisadoes This fix was for a good UI experience. The error message that `the entered password is not at least 8 characters long` was being displayed even when the user had already entered a password with more than 8 characters. 

The fix is to automatically remove that message if the entered password is greater than 8 characters.

@arushi2715 You may continue.

2023-03-10 13:18 UTC, arushi2715 commented
Sure @xoldyckk I'll fix it asap.
Thanks.

2023-03-10 20:10 UTC, arushi2715 commented
@xoldyckk @palisadoes I have fixed this issue. Can you please look into this once.

Now when the password id less than 8 characters it shows the usual error warning as shown in below attachment.

![image](https://user-images.githubusercontent.com/78142604/224418130-eba40e32-06bf-4b6a-9c33-ede1298b1f1b.png)

If the password length is greater than 8 character the warning is not shown.

![image](https://user-images.githubusercontent.com/78142604/224418222-94c3ba5b-5bf4-47bc-9ef9-5316192643f2.png)

2023-03-11 12:15 UTC, xoldyckk requested changes

2023-03-11 12:15 UTC, xoldyckk commented on src/screens/LoginPage/LoginPage.tsx
> +                      <span>{''}</span>
I believe a better syntax to do this would be 

```tsx
{signformState.signPassword.length < 8 && <span>{t('atleast_8_char_long')}</span>}
```

2023-03-11 12:15 UTC, xoldyckk commented on src/screens/LoginPage/LoginPage.tsx
> +    // const isVerified = true;
Remove this comment.

2023-03-11 12:15 UTC, xoldyckk commented on src/screens/LoginPage/LoginPage.tsx
> +    // const isVerified = true;
Remove this comment.

2023-03-11 14:54 UTC, arushi2715 commented
Hey @xoldyckk I made the necessary changes. Can you please review them once.

2023-03-11 15:18 UTC, xoldyckk commented
> Hey @xoldyckk I made the necessary changes. Can you please review them once.

You see those comments I made? When you do the things I asked in those comments, you should click on `resolve conversation`. Remember to do this from now on.

2023-03-11 15:19 UTC, xoldyckk submitted a review, later dismissed

2023-03-11 15:21 UTC, arushi2715 commented
Sure @xoldyckk I'll keep this in mind.

2023-03-11 15:28 UTC, xoldyckk commented
@arushi2715 One more thing. What is the initial UI behaviour when client first lands on sign up page? It wouldn't be good to just continously display that error message. It only makes sense when the client has altered the password field at least once.

A simple approach for this would be making default value of password null. If client enters something that password state will get rewritten to a string. Now, even if client clears their password, the password state will have an empty string `""` in state instead of null value.

So, in your check you can check that if password value is null don't display the message, but if it is an empty string display it. This will make sure that client doesn't see the password is too short error right when they first land on that page.

2023-03-11 15:33 UTC, arushi2715 commented
@xoldyckk yeah this makes sense and it will be a better approach to deal with password error.
I'll make the changes.

2023-03-11 15:37 UTC, xoldyckk commented
> @xoldyckk yeah this makes sense and it will be a better approach to deal with password error. I'll make the changes.

Make sure you leave useful comments to let others understand why you did it this way. Don't worry about comments cluttering the codebase. Comments are good.

2023-03-11 15:51 UTC, arushi2715 commented
@xoldyckk can we not make a state regarding if our input is focused or not and then we can update the state when that text field is clicked on. So, basically we won't display the message until our text field is not focused but as soon as it is clicked we will display it? Do you think this will be a better approach for handeling this?

2023-03-11 16:06 UTC, xoldyckk commented
> @xoldyckk can we not make a state regarding if our input is focused or not and then we can update the state when that text field is clicked on. So, basically we won't display the message until our text field is not focused but as soon as it is clicked we will display it? Do you think this will be a better approach for handelling this?

Both are viable approaches. Just think about what is easier and do that.

2023-03-11 16:48 UTC, arushi2715 commented
@xoldyckk can you please review it once?

2023-03-11 16:57 UTC, xoldyckk commented
@arushi2715 Can you record a short video?

2023-03-11 17:40 UTC, arushi2715 commented
Hey @xoldyckk you can check the attachment linked below.

https://user-images.githubusercontent.com/78142604/224503385-76112304-4f7f-4b32-b808-a5efafdb4830.mp4

2023-03-12 12:52 UTC, xoldyckk commented
@arushi2715 Looks good. You also have to write the corresponding tests for testing UI behaviour for some of the steps I mentioned.

2023-03-12 13:05 UTC, palisadoes commented
> @arushi2715 Looks good. You also have to write the corresponding tests for testing UI behaviour for some of the steps I mentioned.

If the tests are required, why approve it?

2023-03-12 14:01 UTC, arushi2715 commented
@xoldyckk can you please explain a bit? Also, should I do this it in this PR only or open a new issue for the same?

2023-03-12 14:42 UTC, xoldyckk commented
> @xoldyckk can you please explain a bit? Also, should I do this it in this PR only or open a new issue for the same?

You have to test that when `focus` and `blur` events happen for password input field, the warning is displayed according to the `<8` logic. You have to attach the tests within this PR. Whenever you fix an issue, or add a new feature the unit tests need to be written along as well.

2023-03-12 14:47 UTC, arushi2715 commented
Hey @xoldyckk thanks for explaining.
Sure, I'll keep this in mind and will add the test cases for this asap.

2023-03-12 21:38 UTC, arushi2715 commented
@xoldyckk can you check it once please?

2023-03-13 12:13 UTC, xoldyckk commented
@arushi2715 You're using the error message to query for its html element. I think that's a bad practice for something which can easily change. Instead you should make use of some test id for the element which holds that message. Change that.

Everything else looks fine.

2023-03-13 12:34 UTC, arushi2715 commented
@xoldyckk changed it. Can you review it once?

2023-03-13 14:47 UTC, xoldyckk approved these changes
Looks good. Nice job.

2023-03-13 16:40 UTC, palisadoes approved these changes

2023-03-13 16:47 UTC, palisadoes commented
Please lint the code so that the tests can pass.

2023-03-13 17:07 UTC, arushi2715 commented
@palisadoes can you please check it once?

2023-03-13 17:26 UTC, arushi2715 commented
@xoldyckk @palisadoes one test case is failing in ` src/screens/OrganizationEvents/OrganizationEvents.test.tsx` due to which the code coverage is not being shown.

2023-03-13 17:40 UTC, palisadoes approved these changes

2023-03-13 17:41 UTC, merged