fixed warning for OrgUpdate
PalisadoesFoundation/talawa-admin pull request #610
Opened 2023-03-09 15:28 UTC by akankshat05

**What kind of change does this PR introduce?**

bugfix
**Issue Number:**

Fixes #574 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**
![orgupdate](https://user-images.githubusercontent.com/72144454/224071335-8ab127f2-be9d-4e1e-a7f6-7a35d372e0bf.png)

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2023-03-09 16:47 UTC, anshgoyalevil commented
@akankshat05 

Why have you changed the ```OrgUpdate.tsx``` file? It will break the functionality for Organization Update.

Please make changes to test file, and only make changes to Component file if necessary, keeping its functionality in mind.

2023-03-09 16:56 UTC, aviraldevv commented on src/components/OrgUpdate/OrgUpdate.tsx
> +          id: props.id,
@akankshat05 I didn't get why you've to change this it will break the functionality ;)

2023-03-09 16:56 UTC, anshgoyalevil requested changes
Please replace ```props.id``` with ```currentUrl``` or you may implement a better and working approach for this file.

2023-03-10 08:51 UTC, akankshat05 commented
I will make the required changes.

2023-03-14 19:40 UTC, noman2002 commented
@akankshat05 Any progress on this ?

2023-03-15 01:08 UTC, akankshat05 commented
> @akankshat05 Any progress on this ?

I could not come up with a good solution other than hiding the warning. Should I make those changes?

2023-03-15 01:11 UTC, anshgoyalevil commented
@akankshat05 

Yes, you may hide the warning using Mocklink for now.

Please resolve the changes requested above.

2023-03-17 11:12 UTC, palisadoes requested changes
See comments

2023-03-17 11:12 UTC, palisadoes commented on src/components/OrgUpdate/OrgUpdate.test.tsx
> +const mocklink = new MockLink(MOCKS, false, { showWarnings: false });
Hiding warnings is not a solution. Please remove this

2023-03-24 15:02 UTC, palisadoes commented
Please fix the failing tests and the conflicting files. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

2023-03-26 21:03 UTC, akankshat05 commented
@palisadoes The issue which this PR was addressing was fixed by #745

2023-03-27 03:24 UTC, palisadoes commented
Closing

2023-03-27 03:24 UTC, closed without merging