Added prompt to Register on Login Page
PalisadoesFoundation/talawa-admin pull request #628
Opened 2023-03-09 21:45 UTC by Wineshuga

**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #609

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

![Talawa Admin - Google Chrome 3_9_2023 9_59_16 PM](https://user-images.githubusercontent.com/99335288/224166513-44b4c0ea-76ef-44b4-9a3b-8df6111b9753.png)

**Summary**
The Login Page had a Register button for users who do not own an account. But this was not indicated. This pull request solves that problem.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-10 19:02 UTC, noman2002 requested changes
Fix the failing test

2023-03-16 11:06 UTC, Wineshuga commented
Yes I'm still on it. Struggling to figure out why the test is failing though. Any suggestions or advice please?

2023-03-16 23:11 UTC, palisadoes commented
@Kevoniat @noman2002 Please review. The tests are passing.

2023-03-17 17:54 UTC, noman2002 approved these changes

2023-03-17 18:10 UTC, palisadoes approved these changes

2023-03-17 18:10 UTC, merged