password review feature
PalisadoesFoundation/talawa-admin pull request #629
Opened 2023-03-09 23:18 UTC by Aimanosi

**What kind of change does this PR introduce?**
password review feature on the log-in modal page.

**Issue Number:**
Fixes issue
- #612 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/104039356/224178475-63b82528-b34b-4e28-88ed-417e824e487e.mp4

**If relevant, did you update the documentation?**

**Summary**
I created a label tag with text "show" on the right side of the password input field and attached a toggle onclick function to display the password when it is clicked so that users can confirm their password before they log-in.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

2023-03-09 23:21 UTC, Aimanosi commented
HI @palisadoes This PR is ready for review, please let me know if you want me to do anything else, thank you.

2023-03-10 02:52 UTC, palisadoes commented
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

2023-03-10 03:17 UTC, palisadoes commented
Please add tests for the lines mentioned here:

- https://github.com/PalisadoesFoundation/talawa-admin/pull/629/files

We need to maintain our reliability

2023-03-10 03:17 UTC, palisadoes requested changes
Please add tests for the lines mentioned here:

- https://github.com/PalisadoesFoundation/talawa-admin/pull/629/files

We need to maintain our reliability

2023-03-10 06:45 UTC, Aimanosi commented
Hi Peter,

Thank you so much for the help, I made a PR and was told to do a review,
which is adding tests to a line in my code, i have never done this before
so I am a little confused on how to start the process, a little help from
you will mean the world to me, thank you.

Find attached the images from the changes requested.

On Fri, Mar 10, 2023 at 4:17 AM Peter Harrison ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please add tests for the lines mentioned here:
>
>    - https://github.com/PalisadoesFoundation/talawa-admin/pull/629/files
>
> We need to maintain our reliability
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PalisadoesFoundation/talawa-admin/pull/629#pullrequestreview-1334110280>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYZYHPHDU6IPXC6IR3ZYOUDW3KMOJANCNFSM6AAAAAAVVXPJXQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-10 17:12 UTC, Aimanosi commented
HI @palisadoes This PR is ready for review, please let me know if you want me to do anything else, thank you.

2023-03-10 19:12 UTC, palisadoes approved these changes

2023-03-10 19:24 UTC, noman2002 approved these changes

2023-03-10 19:25 UTC, Tajcore submitted a review, later dismissed
Lgtm

2023-03-10 20:53 UTC, palisadoes submitted a review, later dismissed
Please fix the failing tests

2023-03-11 09:37 UTC, Aimanosi commented
Hi @palisadoes @Tajcore @noman2002 @heyjordn 

Thanks for your help thus far, however I'm finding it quite challenging to solve this new test fail, Initially I wrote a test to include the changes I made in the codebase and that gave me a 100% coverage on the "loginPage.tsx" and it passed the first test fail I had, could the test fails in the other files I didn't work on be responsible for this new fails(
PR Workflow / Shows code coverage (pull_request))? if so, how do I resolve this?
![terminal result 001](https://user-images.githubusercontent.com/104039356/224476859-363131ac-f3e9-4b97-ab80-f84337e936bc.jpg)
![terminal result 02](https://user-images.githubusercontent.com/104039356/224476865-079443fb-d6c2-4b8d-b192-539c65c83c23.jpg)


Thank you.

2023-03-11 16:15 UTC, kayceeDev commented on src/screens/LoginPage/LoginPage.test.tsx
> +    const { getByTestId } = render(
Why are yoy destructuring `getByTestId`? Won't `screen.getByTestId` work?

2023-03-11 19:32 UTC, Aimanosi commented
Hi @palisadoes please review this, thank you.

2023-03-11 19:52 UTC, kayceeDev requested changes

2023-03-11 19:52 UTC, kayceeDev commented on src/screens/LoginPage/LoginPage.module.css
> +/* = Nasiru's hide and show password style = */
Could you remove this comment? It is unnecessary and doesn't do anything. Also, this is a public repository and it is not advised to add your name to the comment. The git commit with your name is enough. Make sure there is a consistent line break.

2023-03-11 19:52 UTC, kayceeDev commented on src/screens/LoginPage/LoginPage.tsx
> +  const [show, setShow] = useState(false);
Since we are using typescript, you should type this e.g `useState<boolean>(false)`

2023-03-11 21:14 UTC, kayceeDev approved these changes
Well done!! LGTM✅

2023-03-11 22:05 UTC, Aimanosi commented
Hi @palisadoes please review this, thank you.

2023-03-12 20:17 UTC, Aimanosi commented
Hi @palisadoes @Tajcore @noman2002 
Please review this, thank you.

2023-03-13 16:53 UTC, palisadoes approved these changes

2023-03-13 16:53 UTC, merged