Added check for filtered list of organization
PalisadoesFoundation/talawa-admin pull request #725
Opened 2023-03-16 08:26 UTC by resonating-homesh

**What kind of change does this PR introduce?**

While searching for an organization, if there is no organization with the searched name, then it will alert the user by displaying 'No Organization found!'

**Issue Number:**

Fixes #692 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

![p4](https://user-images.githubusercontent.com/75970868/225556902-0c212ff9-7f63-47fa-9243-b70b2b180ace.jpg)

**If relevant, did you update the documentation?**

Not Relevant

**Summary**

While searching for organizations in case the user has a huge list of organizations, a query with no indicator acts as a degrading factor in terms of user experience. Adding an indicator that alerts users whether there is any organization that they queried for solves this issue.

**Does this PR introduce a breaking change?**

No

**Other information**

Null

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-16 15:27 UTC, palisadoes approved these changes

2023-03-16 16:19 UTC, palisadoes commented
Please fix the failing tests

2023-03-17 07:52 UTC, anshgoyalevil commented
@resonating-homesh 

Please update the ```OrgList.test.tsx``` as you have changed ```OrgList.tsx```

Use MockLink while rendering components. An example here: https://github.com/PalisadoesFoundation/talawa-admin/pull/737/files

2023-03-17 12:16 UTC, palisadoes requested changes
Please update the corresponding tests

2023-03-17 13:12 UTC, resonating-homesh commented
While running the tests on my local machine it is passing all the tests.
![p5](https://user-images.githubusercontent.com/75970868/225914482-a409950a-f702-4c54-b092-3b7048f5791f.jpg)

2023-03-17 14:12 UTC, palisadoes requested changes

2023-03-17 14:12 UTC, palisadoes commented on src/screens/OrgList/OrgList.tsx
> +          setNoResult(true);
Please write a test for this. We don't want it to happen again.

2023-03-17 14:12 UTC, resonating-homesh commented
I am getting this error while running tests.
![Uploading p6.jpg…]()
Can someone help me?

2023-03-18 04:14 UTC, DMills27 commented
Any update on this @resonating-homesh ?

2023-03-18 04:25 UTC, palisadoes commented
Please fix the conflicting files

2023-03-18 07:54 UTC, resonating-homesh commented
> Any update on this @resonating-homesh ?

I don't know how to write test files..I am trying to learn it...

2023-03-18 07:55 UTC, resonating-homesh commented
> > Any update on this @resonating-homesh ?
> 
> I don't know how to write test files..I am trying to learn it...

It would be really helpful if someone could guide me with it...

2023-03-18 18:48 UTC, palisadoes commented
1. Please look at other test examples for files in the same directory.
1. Ask the slack channel
1. Research typescript testing on Google

2023-03-19 14:43 UTC, saadabban76 commented
> 1. Please look at other test examples for files in the same directory.
> 2. Ask the slack channel
> 3. Research typescript testing on Google

I've already worked on this issue and added the postNotFound reusable component to the orgList page, also PR is merged succesfully 👍🏼 #717

2023-03-19 14:48 UTC, palisadoes commented
Does this mean this PR needs to be closed and then issue was a duplicate? @saadabban76

2023-03-19 14:56 UTC, saadabban76 commented
> Does this mean this PR needs to be closed and then issue was a duplicate? @saadabban76

I worked on the reusable postNotFound component for the posts query searches, since it was a reusable component, I used it in the orgList for the organization query search.

2023-03-19 14:58 UTC, saadabban76 commented
> > Does this mean this PR needs to be closed and then issue was a duplicate? @saadabban76
> 
> I worked on the reusable postNotFound component for the posts query searches, since it was a reusable component, I used it in the orgList for the organization query search.

check out this screenshot : https://github.com/PalisadoesFoundation/talawa-admin/pull/717#issuecomment-1473990134

2023-03-19 15:06 UTC, palisadoes commented
Closing. Duplicate issue and PR

2023-03-19 15:06 UTC, closed without merging