fixed the issue of Toast msg is not available in all languages #740
PalisadoesFoundation/talawa-admin pull request #750
Opened 2023-03-18 07:39 UTC by Sumitmaithani

**What kind of change does this PR introduce?**
bugfix

**Issue Number:**
Fixes [#740](https://github.com/PalisadoesFoundation/talawa-admin/issues/740)

**Did you add tests for your changes?**
Not required

**Snapshots/Videos:**
![塔拉瓦郵報 - Google Chrome 3_18_2023 12_25_30 AM](https://user-images.githubusercontent.com/86047367/225993792-af687b92-ee43-4231-9053-52970cd2faff.png)
![तलावा भूमिकाएं - Google Chrome 3_18_2023 12_24_58 AM](https://user-images.githubusercontent.com/86047367/225993838-54825411-09d4-4ba2-a0ab-62fffa1efdbf.png)

**Summary**
Updated all toast msg with all languages.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2023-03-18 17:48 UTC, palisadoes requested changes
The aim of having keys that were English sentences versus versus keys was to make sure that it would be immediately readable without someone constantly having to refer to the JSON files.  This would make programming more efficient.

Please revert the changes so that the original text is restored. Use sentence based keys for any of the new messages you require.

2023-03-18 19:09 UTC, Sumitmaithani commented
> The aim of having keys that were English sentences versus versus keys was to make sure that it would be immediately readable without someone constantly having to refer to the JSON files. This would make programming more efficient.
> 
> Please revert the changes so that the original text is restored. Use sentence based keys for any of the new messages you require.

Okay like this right
"Talawa-APIServiceIsUnavailable.IsItRunning?CheckYourNetworkConnectivityToo": "Talawa-API service is unavailable. Is it running? Check your network connectivity too."

2023-03-18 19:39 UTC, palisadoes commented
Take guidance from what was there before.

2023-03-19 14:30 UTC, palisadoes commented
@sumitra19jha We'll need your opinion on this as it relates to translations

2023-03-24 12:19 UTC, palisadoes commented
Please fix the merge conflicts and the tests

2023-03-24 14:54 UTC, palisadoes submitted a review, later dismissed

2023-03-24 14:54 UTC, palisadoes commented
Please fix the conflicting files

2023-03-24 15:10 UTC, palisadoes commented
Please fix the failing tests

2023-03-24 16:32 UTC, palisadoes commented
Please fix the failing tests.

2023-03-25 11:34 UTC, Sumitmaithani commented
@palisadoes I've done all the test cases from 30% to 88.88% only 1.42% remains due to AddOnRegister where add plugin functionality is not added that cause that test case cannot be covered right now but when functionality of plugin added we can covered test cases their also..

2023-03-25 14:43 UTC, palisadoes submitted a review, later dismissed

2023-03-28 18:27 UTC, Sumitmaithani commented
@palisadoes 

This PR can now be merged.

2023-03-28 18:29 UTC, palisadoes commented
Please read the Our Pull Request Approval Process comment in its entirety

2023-03-29 16:52 UTC, Rumone commented on public/locales/en.json
> +    "toastError8": "User not found!",
Why is it toastError1..8 and not a more appropriate name based on the string it represents.

2023-03-29 16:55 UTC, Rumone commented on public/locales/en.json
> +    "toastError": "Talawa-API service is unavailable. Is it running? Check your network connectivity too.",
Why not use a more appropriate name that represent the message. I see toastError as too ambiguous and could lead to potential confusion for future devs.

2023-03-29 16:59 UTC, Rumone commented
The main and only issue I have with this PR is the use of inappropriate names for  strings in the localization files.

2023-03-29 18:28 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

2023-03-30 04:42 UTC, Rumone commented on public/locales/en.json
> +    "toastError": "Talawa-API service is unavailable. Is it running? Check your network connectivity too.",
For the message "Talawa-API service is unavailable. Is it running? Check your network connectivity too." The property name `talawaApiUnavailable` should suffice.

2023-03-30 04:44 UTC, Rumone commented on public/locales/en.json
> +    "toastError": "Talawa-API service is unavailable. Is it running? Check your network connectivity too.",
Congratulation_the_Organization_is_created could be `createOrgSuccess`

2023-04-01 20:38 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

2023-04-02 04:49 UTC, Sumitmaithani commented
@palisadoes yes I m working on it.

2023-04-05 10:26 UTC, Sumitmaithani commented
I m closing this PR. please review this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/845) for this issue.

2023-04-05 10:26 UTC, closed without merging