added UserNotFound component to the Roles page and improved the search
PalisadoesFoundation/talawa-admin pull request #799
Opened 2023-03-25 01:49 UTC by Pranauv-Kumar1803

**What kind of change does this PR introduce?**
Fixed the search by name in Roles page so that now, when there are no users present, it will show 'UserNotFound' instead of giving unnecessary results and added userNotFound component along with its translations to the Roles page.

**Issue Number:**
Fixes #613 

**Did you add tests for your changes?**
Yes.

**Snapshots/Videos:**
https://user-images.githubusercontent.com/97829544/227679036-10cf4a5b-6196-40c3-bd89-e1faf65be6e3.mp4

**If relevant, did you update the documentation?**
Not Relevant.

**Summary**
Made the search by name in Roles section better by making it check for errors from graphql ( given when a user is not found ) and also made the postNotFound component as reusable and implementing it in the Roles section. Also added a new key in locales to convert it into other languages.

**Does this PR introduce a breaking change?**
Small change but better user experience.

**Other information**

None.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes.

2023-03-25 05:31 UTC, palisadoes commented
Please fix the failing tests

2023-03-25 05:33 UTC, Pranauv-Kumar1803 commented
yes sir, I'm working on it

2023-03-25 14:30 UTC, Pranauv-Kumar1803 commented
Can some one help me in solving this issue?

2023-03-25 15:11 UTC, palisadoes commented
Please ask on the #talawa-admin slack channel

2023-03-28 14:44 UTC, Pranauv-Kumar1803 commented
@palisadoes Pls Review!

2023-03-30 02:42 UTC, Pranauv-Kumar1803 commented on src/screens/Roles/Roles.test.tsx
> -  test('Should render warning alert when there are no organizations', async () => {
I removed it because in organizations has nothing to do with Roles page because roles is only for users(admin/superadmin)

2023-03-30 02:42 UTC, Pranauv-Kumar1803 commented on src/screens/Roles/Roles.tsx
> +                      <PostNotFound title="user" keyPrefix="userNotFound" />
Ok Ill change the component name to "NotFound" component.

2023-03-30 04:08 UTC, Kevoniat commented on src/screens/Roles/Roles.test.tsx
> -  test('Should render warning alert when there are no organizations', async () => {
@Pranauv-Kumar1803  was the testing failing?

2023-03-30 04:46 UTC, Rumone commented on src/screens/Roles/Roles.tsx
> +                      <PostNotFound title="user" keyPrefix="userNotFound" />
That works 👍🏽

2023-03-30 04:59 UTC, ttaylor92 requested changes

2023-03-30 04:59 UTC, ttaylor92 commented on src/screens/Roles/Roles.test.tsx
> -  test('Should render warning alert when there are no organizations', async () => {
Once this issue hase been resolved we can have this approved

2023-03-30 05:34 UTC, Pranauv-Kumar1803 commented on src/screens/Roles/Roles.test.tsx
> -  test('Should render warning alert when there are no organizations', async () => {
@Kevoniat yes it was failing

2023-03-31 11:25 UTC, Pranauv-Kumar1803 commented
@ttaylor92 Can u pls answer my questions? If i get those answered i could make changes and push them

2023-04-02 05:30 UTC, Pranauv-Kumar1803 commented
> @ttaylor92 Can u pls answer my questions? If i get those answered i could make changes and push them [#799 (comment)](https://github.com/PalisadoesFoundation/talawa-admin/pull/799#discussion_r1153094460)

@ttaylor92 Pls answer so that i can push my changes or work on it

2023-04-04 02:15 UTC, Pranauv-Kumar1803 commented
@noman2002 Pls reply to my questions above so that i can change whichever is needed and push it!

2023-04-11 09:26 UTC, closed without merging

2023-04-11 11:16 UTC, Pranauv-Kumar1803 commented
did the same in a new pr #865 
pls look there because this was closed due to sync fork!
sorry for the inconvenience!