Added:  Date Picker view in the events section
PalisadoesFoundation/talawa-admin pull request #823
Opened 2023-03-30 01:45 UTC by aashimawadhwa

**What kind of change does this PR introduce?**

feature
**Issue Number:**

Fixes #627 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**
![Screenshot 2023-03-30 at 7 07 03 AM (2)](https://user-images.githubusercontent.com/73706697/228706579-0f705e07-300c-4765-b816-17d5101a0f1f.png)

**If relevant, did you update the documentation?**

Not required
**Summary**

Implemented date picker and removed the old filters that worked for event tiles and not the calendar.
**Does this PR introduce a breaking change?**

no
**Other information**

not any
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
yes

2023-03-30 04:42 UTC, ttaylor92 requested changes
Please cover the line marked by code coverage as we do not want to decrease the overall coverage percentage currently existing.

2023-03-30 18:09 UTC, EshaanAgg commented
@aashimawadhwa You have simply removed the code for functionality that allows to filter by `Title`, `Description` and `Location`. Is there a specific reason for it?

2023-03-30 18:31 UTC, aashimawadhwa commented
@EshaanAgg The calendar for talawa is inspired from google calendar. if you look closely to the calendar  we have search functionality and a small calendar in the sidebar, even at breeze chms we have the styling the same way.

Therefore we are removing the filter functionality for now

2023-03-30 18:44 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

2023-03-30 18:54 UTC, Rumone commented
> @EshaanAgg The calendar for talawa is inspired from google calendar. If you look closely to the calendar we have a small calendar in the sidebar, even at breeze chms we have this in the same way.
> 
> 
> 
> Therefore we are removing the filter functionality for now and adding the small calendar.
I don't see the benefit of removing the existing filter functionality. Would they not provide valuable results to the user? The mini calendar could augment the existing filter 
**Example** Filter by a specific title and a date.

2023-03-30 19:03 UTC, aashimawadhwa commented
@Rumone  the location and description is not a properly defined therefore I don't think it will be a good parameter to search for user, and this calendar implemented  is not for users specifically it is focused on the super admins of the organization as of now.

2023-03-30 21:21 UTC, EshaanAgg commented
@aashimawadhwa Earlier, the `Description` and `Location` fields were also shown on the dashboard; thus, they made good candidates to filter events. Since now only the `Title` field is shown on the UI, at least the support to filter by the same should be provided and not deprecated.

The date picker can be used in two ways:
1. To change the focus of the calendar (which month or day I am exploring)
2. As a filter to sort by date (and date ranges)
What do you think would be a better functionality from a long-term prospect?

2023-03-30 21:22 UTC, EshaanAgg commented on src/screens/OrganizationEvents/OrganizationEvents.tsx
> -  };
As you can see here, the filtering indeed does work (via an API call to the backend).

2023-04-01 20:40 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

2023-04-09 16:28 UTC, palisadoes commented
Please fix the failing tests

2023-04-10 21:14 UTC, aashimawadhwa commented
Sir, I am making  some changes, will update this ASAP. @palisadoes

2023-04-12 21:41 UTC, aashimawadhwa commented
@palisadoes Sir, can you close this PR, I will raise a new one. This is having a lot of conflicts which I am unable to solve.

2023-04-12 22:08 UTC, closed without merging