Fix Password validation on the Login/Signup Page [Fixes #720]
PalisadoesFoundation/talawa-admin pull request #846
Opened 2023-04-05 15:03 UTC by BhuvanAde

**What kind of change does this PR introduce?** 
It is a bug fix; the password validation during the signup only constrain the password on being non-empty but now it will ensure that it is at least 8 characters long and has at least one capital letter, one number and one special character.

**Issue Number:**
#720 

Fixes #720 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

2023-04-05 15:15 UTC, BhuvanAde commented
This PR currently solves the issue, but it may be extended to have other language supports as well which needs discussion. The critical thing right now was syncing the mobile password rules with the admin panel, thus I have raised this PR.

2023-04-05 19:57 UTC, BhuvanAde commented
@noman2002 I added some validations on the password field while registering on the admin portal.

2023-04-06 01:47 UTC, ttaylor92 requested changes
Please ensure to add the .yarn folder to the gitignore file so as to avoid pushing npm packages to repo. Update and resubmit for review

2023-04-06 04:57 UTC, BhuvanAde commented
@ttaylor92 I Fixed that! please check

2023-04-06 20:15 UTC, Rumone requested changes

2023-04-06 20:15 UTC, Rumone commented on src/screens/LoginPage/LoginPage.tsx
> +      console.log('yes');
Is this still being used?

2023-04-06 20:25 UTC, BhuvanAde commented on src/screens/LoginPage/LoginPage.tsx
> +      console.log('yes');
Removed!

2023-04-09 07:30 UTC, anshgoyalevil commented
@BhuvanAde 

Please pull the latest code, and re-run the tests.

2023-04-14 04:04 UTC, BhuvanAde commented
@ttaylor92 @Rumone I have sent another PR with the required changes and I'll close this PR. I request you to please review #881

2023-04-14 04:04 UTC, closed without merging