Organization People Filters Improved
PalisadoesFoundation/talawa-admin pull request #855
Opened 2023-04-07 15:40 UTC by prathamesh-mutkure

**What kind of change does this PR introduce?**

Bug Fix

**Issue Number:**

Fixes #730 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

<img width="1883" alt="Screenshot 2023-04-07 at 9 06 58 PM" src="https://user-images.githubusercontent.com/28570857/230636487-eea7e1ff-ffcf-4316-a831-15c832676950.png">

<img width="1883" alt="Screenshot 2023-04-07 at 9 07 55 PM" src="https://user-images.githubusercontent.com/28570857/230636644-9e6bf493-4722-46da-a383-3fda97717e4a.png">

**If relevant, did you update the documentation?**

Not Relevant

**Summary**

The problem -

- The Organization People's page filter didn't work as intended
- The user couldn't search by `lastName`
- The filters didn't work for `users` and `admins`
- The page unnecessarily reloaded after a change in the search query

Changes -

- Added a new field to search by `lastName`
- Added filters to `users` and `admins` as well
- The complete page no longer reloads
- Only the table reloads  

**Does this PR introduce a breaking change?**

No

**Other information**

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

2023-04-07 15:44 UTC, prathamesh-mutkure commented
Looks like I'll have to add more tests

2023-04-08 15:39 UTC, Kevoniat approved these changes

2023-04-09 03:30 UTC, palisadoes commented
Please fix the conflicting files

2023-04-09 06:16 UTC, prathamesh-mutkure commented
Key @Kevoniat, I've fixed the merge conflicts.

Can you please approve this again?

2023-04-09 14:22 UTC, palisadoes commented
Please merge your code with the latest upstream

2023-04-09 15:20 UTC, prathamesh-mutkure commented
@palisadoes done!

2023-04-10 09:32 UTC, prathamesh-mutkure commented
Hey, @noman2002 can you please review this?

2023-04-10 14:23 UTC, Kevoniat submitted a review, later dismissed

2023-04-10 16:15 UTC, palisadoes requested changes
Please review my questions

2023-04-10 16:15 UTC, palisadoes commented on public/locales/en.json
> +    "searchevent": "Enter Event",
Why aren't the JSON files for other languages updated?

2023-04-10 18:07 UTC, palisadoes approved these changes

2023-04-10 18:08 UTC, merged